### ISSUE TITLE
remove bridge tile on main home (favorites) screen

### ISSUE THREAD

**Issue by thecem** [ebaauw/homebridge-nb#13]
Thank you for this great plugin!

Is there a possibility to remove the "Nuki_Bridge_XXXXXXX" tile in the main home screen (favorites) and have it only in a separate room (standard room) like the (not supported) "Philips hue" and "Phoscon-GW" bridge which are only showed in a room but not in the main overview.

Thanks a lot for you help in advance!

**Comment by ebaauw** [comment]
Not from iOS 14 nor from macOS Big Sur.  If you still have an old iOS or macOS version running Home, you can unset the favourite state from there, and it will be propagated to iOS 14.  Otherwise, I need to expose the bridge as something that Home likes, probably a dummy _Stateless Programmable Switch_, like the Hue bridge or deCONZ gateway accessory.

**Comment by thecem** [comment]
Indeed, I configured it a long time ago and can’t remember, if the bridge tile of hue and or deconz was also shown in the favorites.
But I don’t have a “old” iOS before 14. So it would useful to move those tiles in a different room and remove it from favorites. 
what do you think?

**Comment by ebaauw** [comment]
v1.0.3 exposes a dummy _Stateless Programmable Switch_ service on the bridge accessory.  It will never trigger, so the associated action will never be executed.

**Comment by thecem** [comment]
How nice is this! Unbelievable! So fast! Thanks a lot!
I tried it and it works like a charm!
