### ISSUE TITLE
Push notifications delay/skipped

### ISSUE THREAD

**Issue by cerahmed** [ebaauw/homebridge-nb#145]
Hey @ebaauw,

Many thanks for this great plugin. Been rocking it since I got my Nuki Locks for quite some time now and it is solid.

I noticed this issue a while back, but it started bothering me so I thought I could bring it up for some help. I have multiple Nuki Locks 2.0 connected via bluetooth to the Nuki Hub, which is configured with this plugin. Each lock has a door sensor connected to it, which used to notify me instantly as I open/close the door.

Recently (a few months back), the notifications from the lock (locking operations, door sensor) is a few seconds (up to 2 minutes sometimes) late; I noticed even that it sometimes skips a few operations.

I don't know if it's Nuki's part, but I wish if you could help troubleshoot the issue as the notifications are unreliable unlike the rest of the plugin.

Many thanks in advance.

**Comment by ebaauw** [comment]
In my experience push notifications aren't always reliable.  Also, I find the Nuki door sensor to be far less reliable than a simple Zigbee door sensor by Aqara.  I think the problem is the communication between the Nuki smart lock and the Nuki bridge.  When using lock 'n' go, the lock engages as soon as I close my door, suggesting the communication between the sensor and the smart lock is OK.  BLE remains a troublesome protocol in my experience.  I now have a smart lock 3.0 that I also expose natively to HomeKit over Thread.  The native accessory seems quicker respond than the one by Homebridge NB. 

As for troubleshooting:
- Most issues disappear after power cycling the Nuki bridge.  Until they re-appear, but in my experience that takes weeks or months;
- Double check the callback list on the Nuki bridge (`nb callbackList`).  Make sure Homebridge NB is the first entry.  In my experience further callbacks are cancelled after a failed one;
- Turn on logging in Homebridge NB, to monitor the callbacks received.  You could also use `nb eventlog`, but that uses another callback entry.  Also check the Homebridge log for errors, timeouts, etc.
- Don't use other Nuki bridge clients.  The Nuki bridge is not very powerful, and multiple clients polling it might lead to performance issues.  Use a conservative polling rate for Homebridge NB.
- Check in the Nuki app that the Nuki bridge is connected to the Nuki smart lock.
