### ISSUE TITLE
No Notififcation

### ISSUE THREAD

**Issue by jlngnr** [ebaauw/homebridge-nb#18]
Hello,

your Plugin just works fine. Now I have the opener and a smart lock in HomeKit.
But when somebody rings the Doorbell I get not a notification from the Home App. 
And were can i find the Doorbell in EVE?

**Comment by ebaauw** [comment]
It’s exposed as service on the accessory for the Opener.  Just touch the Opener from the room view, to see its details, with three services: _Doorbell_, _Lock Mechanism_, and _Battery_.

Does _Last Updated_ on the _Doorbell_ change when the bell rings?  If not, the issue is with the Nuki bridge not sending a notification to Homebridge NB.  Otherwise, the issue is with HomeKit.  The _Doorbell_ service seems to be intended for use in a video doorbell accessory only.  It’s invisible in Home, except for the notifications.  You need to create an automation in Eve to link any action.

**Comment by jlngnr** [comment]
It no change when it rings on the Doorbell. How can I fix this?

Am 22.01.2021 um 00:10 schrieb Erik Baauw <notifications@github.com>:

﻿

It’s exposed as service on the accessory for the Opener. Just touch the Opener from the room view, to see its details, with three services: Doorbell, Lock Mechanism, and Battery.

Does Last Updated on the Doorbell change when the bell rings? If not, the issue is with the Nuki bridge not sending a notification to Homebridge NB. Otherwise, the issue is with HomeKit. The Doorbell service seems to be intended for use in a video doorbell accessory only. It’s invisible in Home, except for the notifications. You need to create an automation in Eve to link any action.

**Comment by thecem** [comment]
Do you receive a ring of the doorbell in app? On my side I had to change the cabling for my setup. The opener doesn´t received the signal of the doorbell correctly, after I changed the cabling setup I had also to change the nuki opener config.

**Comment by jlngnr** [comment]
Yes when I activate „Nuki Web“. But I cannot deactivate the ringing of my doorbell in the App. When I deactivate the bell it rings anyway.  Maybe it's related.  How did they change the wiring.  With the help of support?

**Comment by thecem** [comment]
Without the support, I tried some setups, one worked. My doorbell was since not officially supported. But if the nuki app rings the opener is correct connected.

you finde it in the eve App opener menu:

![4B38992F-4265-4E67-9E08-2B1D14E6EC11](https://user-images.githubusercontent.com/46648579/105490478-208ed680-5cb5-11eb-8935-216c68b73056.jpeg)

enabled ein: rings
Enabled aus: rings not

**Comment by thecem** [comment]
For a better understanding, which bell?

- The old doorbell connected to the door?
   This one is only configured in nuki app
- Nuki app notify
   See above
- HomeKit notify
   Eve App as described above
- HomePod Ring
   Eve App as described above

**Comment by jlngnr** [comment]
> For a better understanding, which bell?
> 
> * The old doorbell connected to the door?
>   This one is only configured in nuki app
> * Nuki app notify
>   See above
> * HomeKit notify
>   Eve App as described above
> * HomePod Ring
>   Eve App as described above

The old Doorbell. I thinking the slider was for that to deactivate. 
Where in the Eve App I can activate the HomeKit notify and the HomePod ringing?

**Comment by jlngnr** [comment]
> Without the support, I tried some setups, one worked. My doorbell was since not officially supported. But if the nuki app rings the opener is correct connected.
> 
> you finde it in the eve App opener menu:
> 
> ![4B38992F-4265-4E67-9E08-2B1D14E6EC11](https://user-images.githubusercontent.com/46648579/105490478-208ed680-5cb5-11eb-8935-216c68b73056.jpeg)
> 
> enabled ein: rings
> Enabled aus: rings not

And that's exactly what doesn't work for me.  Regardless of whether it is off or on it rings anyway.  But they say yes if I get a doorbell notification via the app, then everything at Nuki is ok and wired correctly.  Maybe I just have to reinstall the plugin.  Maybe something went wrong when installing

**Comment by thecem** [comment]
As mentioned, the old doorbell ring could not disable with the puglin, in HomeKit and Eve. Standard the ring in HomePod is on, and you should receive the notify in HomeKit, if you don´t deactivate this in homekit.

If you would deactivate your old doorbell, you could this only achive in the Nuki app. If this not working in your setup, you need the support of nuki. in some setup or doorbell types it is NOT possible. I my setup I´m able to receive the ring, but I´m not able to deactivate the doorbell at all, because the opener is not able to filter the signal to the doorbell (I my setup!).

**Comment by jlngnr** [comment]
Thanks for your help. Got it done. Unfortunately not with your plugin. Your plugin is too simple and too user-friendly :). Had to do it with Lukas Roegner's plug-in and enter everything into the config myself. But this has a good one. I could only insert the opener and leave the lock in Homekit via the Nuki app. Thanks anyway for all the help :)
