### ISSUE TITLE
Every unlock is an unlatch

### ISSUE THREAD

**Issue by derthobo** [ebaauw/homebridge-nb#25]
Every time I unlock the lock with Homekit, the apartment door opens completely. I have activated the second lock (the "latch"-lock) to fully open the door in the configuration. 

**Is there a way to unlock the lock without opening the door?**

I have already changed the door type in the Nuki app, but unfortunately that hasn't changed anything. The door will still open automatically. 

**Thank you for your great work! 🥰**

**Comment by ebaauw** [comment]
Homebridge NB should unlock the door, irrespective of the door setting (knob vs level).  It unlatches the door on slide from unlock to unlock, see #16, or when exposing the second lock service for unlatch (which totally confuses Siri).

What’s the output of `nb -DD -H `_hostname_`:`_port_`lockAction `_nukiID_ `0 1`?  Does this unlock or unlatch the door?  See `nb -h` for help on the `nb` command.

**Comment by derthobo** [comment]
I've tried about 3 hours to run the command line tool, but I failed 😔 

I'm running the homebridge in a docker container.

**Comment by ebaauw** [comment]
I don't do Docker.  `nb` is distributed with Homebridge NB, so you would need to run it from within the container.  Alternatively, install Homebridge NB on your host system (you don't need to install nor start Homebridge), and run `nb` from there.

I'm not part of the Nuki beta programme.  Conceivably, it could cause issues, but without running `nb` that would be guesswork.  You might try and revert to the regular firmwares on you smart door lock and bridge.

**Comment by derthobo** [comment]
Here is a little update 😌

At first I left the beta program, but a downgrade is unfortunately not possible. So I have to wait for the next stable version.

Meanwhile I set the Nuki Bridge on factory settings and repeated the process to integrate the Nuki Bridge with your plug-in.

Now it seems to work. But: If I lock or unlock the "normal" lock (not the latch-lock) repeatedly, then the apartment door will open unintentionally again.

I'll try it again with the command line tool within the next few days.

**Thank you! 🙂**

**Comment by gielk** [comment]
I'm also confused, but I always open the front door with Siri, unfortunately it's far too slow, and I always get a “no response” response from Siri. Now with this plugin, it works superfast and much more reliable. Only I have a door with a knob. So now when I ask Siri to open the door, it only unlocks. I would like to default when I ask Siri to open the door that it also goes unlatch.

Tried the “Expose a second Lock Mechanism service to unlatch a Smart Lock.”
But here Siri gets completely confused as you say yourself and cannot open this lock at all.

Isn't there an option to choose what happens when I unlock a lock? That he will unlock or unlatch?

**Comment by ebaauw** [comment]
Create a scene in Eve containing the custom _Unlatch_ characteristic and recall that scene from Siri.
