### ISSUE TITLE
Deactivate doorbell ringing for Homepod

### ISSUE THREAD

**Issue by hotdotdev** [ebaauw/homebridge-nb#27]
Besides of the smart lock I have the Nuki Opener. When someone is ringig, then the Homepod is ringing also -> 3 times. I cannot stop this, nor deactivating it in the homekit-settings. Is there a way to deactivate the ringing in the plugin?

**Comment by ebaauw** [comment]
See #7.

**Comment by crouchingtiger** [comment]
Sorry to re-open the thread, but would there be any way you can think of to expose this setting like a real a camera / door bell does? I have multiple HomePods, and since this is a workaround, all my HomePods (9 of them) start ringing, often times after I've already opened the door as they were slower to react.

Normally you can configure this per HomePod in the HomePod settings under [``Use HomePod with a doorbell``](https://support.apple.com/guide/homepod/change-settings-apde6dc8093d/homepod), but this isn't available to me. 

Any ideas? Thanks.

**Comment by ebaauw** [comment]
As far as I understand, this is all HomeKit magic that only works with a video doorbell accessory.  Exposing the opener as a fake video doorbell, with an empty video feed seems way over the top.

Finally managed to order a HomePod mini, even though not available officially in NL, expected delivery later this week.  Primarily for looking at the Thread implementation, but might also have a look at the doorbell options.  Don’t hold any high hopes, though.
