### ISSUE TITLE
Bridge syncs but accessories don't work

### ISSUE THREAD

**Issue by josetomas95** [ebaauw/homebridge-nb#64]
Hi, I´m Jose
I have installed the plugin and managed to pair it with the Bridge perfectly. In Homekit, the lock, the Nuki Opener appear as another lock, and then a doorbell from the Opener. The problem is that pressing to lock or unlock the lock does nothing, pressing the Nuki Opener does not react either.
<img width="1199" alt="Captura de Pantalla 2022-04-21 a las 2 15 09" src="https://user-images.githubusercontent.com/9724206/164344878-06b1b7c7-54f0-41d4-a6af-25d09cf66bc6.png">
<img width="1085" alt="Captura de Pantalla 2022-04-21 a las 2 15 48" src="https://user-images.githubusercontent.com/9724206/164344882-018e4eb9-7bf5-447f-b788-961a3f42c774.png">
![photo_2022-04-21 02 17 01](https://user-images.githubusercontent.com/9724206/164344954-be394a17-9c22-4388-98f7-7d98b7a9bfaa.jpeg)

**Comment by ebaauw** [comment]
The `devicetype` in the requests doesn’t make sense, 2.11.9 is the firmware version; the `devicetype` is a single integer, and should be 0 for the 2.0 smart lock.

https://github.com/ebaauw/homebridge-nb/blob/766c024a3345264fed1eaf6a2ce9b9981e15f741/lib/NbAccessory.js#L299

This doesn’t look good, but I think it’s mitigated when you restart Homebridge, causing `devicetype` To be updated.

**Comment by ebaauw** [comment]
Looking at the code, the wrong value is set when the accessory is initialised, either because it's newly created or restored from persisted cache.  The right value is set when the bridge is polled.  Also the but doesn't affect the Opener.  I think you might have a communication issue between Homebridge NB and the Nuki bridge, unrelated to this bug.  I would need to see the full log for that, please **attach** the log file (rather than copy/pasting large amounts of logs).

**Comment by ebaauw** [comment]
In v1.2.7.
